const data = {
  products: [
    {
      name: "Logitech G Series G435",
      slug: "Logitech-G-Series-G435",
      category: "Inalambrico", 
      image: "/img/auris1.webp",
      price: 15000,
      rating: 4.5,
      countInStock: 20,
      description:
        "El diseño over-ear brinda una comodidad insuperable gracias a sus suaves almohadillas. Al mismo tiempo, su sonido envolvente del más alto nivel se convierte en el protagonista de la escena.",
    },
    {
      name: "Logitech G Series G733",
      slug: "Logitech-G-Series-G733",
      category: "Inalambrico", 
      image: "/img/auris2.webp",
      price: 27000,
      rating: 3.2,
      countInStock: 30,
      description:
        "Tener auriculares específicos para jugar cambia completamente tu experiencia en cada partida. Con los Logitech G733 no te perdés ningún detalle y escuchás el audio tal y como fue diseñado por los creadores.",
    },
    {
      name: "Logitech G Series G332",
      slug: "Logitech-G-Series-G332",
      category: "Inalambrico: NO", 
      image: "/img/auris3.webp",
      price: 9000,
      rating: 4.5,
      countInStock: 35,
      description:
        "Los auriculares Logitech G332 para gaming permiten oír más de lo que pasa en el juego, con transductores grandes de 50 mm que ofrecen una reproducción de sonido completa.",
    },
    {
      name: "HyperX Cloud Flight",
      slug: "HyperX-Cloud-Flight",
      category: "Inalambrico", 
      image: "/img/auris4.webp",
      price: 15000,
      rating: 2.9,
      countInStock: 20,
      description:
        "Ideado para los gamers más exigentes, el HyperX Cloud Flight tiene todo lo que un jugador busca. Su conectividad inalámbrica permite moverte de un lugar a otro sin cables. A su vez, su batería de larga duración te dará horas interminables de sonidos envolventes en tus partidas.",
    },
    {
      name: "HyperX Cloud II",
      slug: "HyperX-Cloud-II",
      category: "Inalambrico", 
      image: "/img/auris5.webp",
      price: 19000,
      rating: 3.5,
      countInStock: 20,
      description:
        "¡Experimentá la adrenalina de sumergirte en la escena de otra manera! Tener auriculares específicos para jugar cambia completamente tu experiencia en cada partida. Con los HyperX Cloud II Wireless no te perdés ningún detalle y escuchás el audio tal y como fue diseñado por los creadores.",
    },
    {
      name: "Razer Kraken",
      slug: "Razer-Kraken",
      category: "Inalambrico: NO", 
      image: "/img/auris6.webp",
      price: 18000,
      rating: 2.4,
      countInStock: 0,
      description: "¡Experimentá la adrenalina de sumergirte en la escena de otra manera! Tener auriculares específicos para jugar cambia completamente tu experiencia en cada partida. Con los HyperX Cloud II Wireless no te perdés ningún detalle y escuchás el audio tal y como fue diseñado por los creadores.",
    },

    //TECLADOS

    {
        name: "Logitech Serie G G915",
        slug: "Logitech-Serie-G-G915",
        category: "Inalambrico", 
        image: "/img/teclado1.webp",
        price: 40000,
        rating: 2.4,
        countInStock: 20,
        description: "G915 TKL Logitech G915 TKL Teclado Mecánico Inalámbrico RGB Con Tecnología Inalámbrica LIGHTSPEED Para Juegos Sin Teclado Numérico - Carbon Distribución De Teclado Inglés Táctil",
      },
      {
        name: "Redragon Kumara K552",
        slug: "Redragon-Kumara-K552",
        category: "Inalambrico: NO", 
        image: "/img/teclado2.webp",
        price: 8000,
        rating: 2.4,
        countInStock: 27,
        description: "Este dispositivo tiene teclas antighosting. Esta cualidad es indispensable si requerís de un uso intensivo del periférico. Gracias a esto podrás evitar fallas al tocar varias teclas al mismo tiempo.",
      },
      {
        name: "Redragon Draconic K530",
        slug: "Redragon-Draconic-K530",
        category: "Inalambrico", 
        image: "/img/teclado3.webp",
        price: 10000,
        rating: 2.4,
        countInStock: 30,
        description: "Tecnología antighosting, este dispositivo tiene teclas antighosting. Esta cualidad es indispensable si requerís de un uso intensivo del periférico. Gracias a esto podrás evitar fallas al tocar varias teclas al mismo tiempo.",
      },
      {
        name: "Redragon Shiva K512",
        slug: "Redragon-Shiva-K512",
        category: "Inalambrico: NO",
        image: "/img/teclado4.webp",
        price: 6000,
        rating: 2.4,
        countInStock: 26,
        description: "Tecnología antighosting, este dispositivo tiene teclas antighosting. Esta cualidad es indispensable si requerís de un uso intensivo del periférico. Gracias a esto podrás evitar fallas al tocar varias teclas al mismo tiempo.",
      },
      {
        name: "Corsair Rapidfire K70",
        slug: "Corsair-Rapidfire-K70",
        category: "Inalambrico: NO",
        image: "/img/teclado5.webp",
        price: 40000,
        rating: 2.4,
        countInStock: 0,
        description: "Este dispositivo tiene teclas antighosting. Esta cualidad es indispensable si requerís de un uso intensivo del periférico. Gracias a esto podrás evitar fallas al tocar varias teclas al mismo tiempo.",
      },
      {
        name: "HyperX Alloy Origins Core",
        slug: "HyperX-Alloy-Origins-Core",
        category: "Inalambrico",
        image: "/img/teclado6.webp",
        price: 15000,
        rating: 2.4,
        countInStock: 16,
        description: "Este dispositivo tiene teclas antighosting. Esta cualidad es indispensable si requerís de un uso intensivo del periférico. Gracias a esto podrás evitar fallas al tocar varias teclas al mismo tiempo.",
      },

      //MOUSES

      {
        name: "Logitech Pro Series Pro X Superlight",
        slug: "Logitech-Pro-Series-Pro-X-Superlight",
        category: "Inalambrico", 
        image: "/img/mouse1.webp",
        price: 19000,
        rating: 2.4,
        countInStock: 23,
        description: "Mayor duración de la batería, con batería recargable incorporada que podés cargar fácilmente con el cable USB incluido sin necesidad de reemplazarla. Para prolongar la duración, usá el conmutador de encendido para apagar el mouse cuando no lo estés usando.",
      },
      {
        name: "Logitech G Series Hero 16K G502",
        slug: "Logitech-G-Series-Hero-16K-G502",
        category: "Inalambrico: NO",
        image: "/img/mouse2.webp",
        price: 9000,
        rating: 2.4,
        countInStock: 40,
        description: "HERO es nuestro sensor para juegos con una precisión de próxima generación y una arquitectura específica. Con el procesamiento de frecuencia de cuadro más rápido hasta la fecha, HERO es capaz de más de 400 ips y 100 - 16.000 dpi, sin suavizado, filtrado ni aceleración. HERO ofrece precisión al más alto nivel competitivo y máxima uniformidad de respuesta. Asegúrate de personalizar y ajustar tu configuración de dpi con Logitech Gaming Software (LGS).1",
      },
      {
        name: "Logitech G Series Lightspeed G305",
        slug: "Logitech-G-Series-Lightspeed-G305",
        category: "Inalambrico", 
        image: "/img/mouse3.webp",
        price: 6000,
        rating: 2.4,
        countInStock: 0,
        description: "G305 es un mouse inalámbrico para juegos LIGHTSPEED diseñado para un desempeño excelente con las innovaciones tecnológicas más recientes a un precio asequible.",
      },
      {
        name: "Corsair Harpoon Wireless",
        slug: "Corsair-Harpoon-Wireless",
        category: "Inalambrico", 
        image: "/img/mouse4.webp",
        price: 14000,
        rating: 2.4,
        countInStock: 20,
        description: "Plug And Play, solo debés colocar el receptor en un puerto USB de la computadora y ya podés empezar a usarlo. No hace falta emparejar el mouse ni descargar software para utilizarlo.",
      },
      {
        name: "Razer DeathAdder Elite",
        slug: "Razer-DeathAdder-Elite",
        category: "Inalambrico: NO",
        image: "/img/mouse5.webp",
        price: 18000,
        rating: 2.4,
        countInStock: 10,
        description: "La funcionalidad al alcance de tu mano, el sistema de detección de movimiento óptico te permitirá mover el cursor de una manera más precisa y sensible que en los sistemas tradicionales. Rapidez y confiabilidad de los botones, con sus 7 botones podrás tener mayor control e independencia para ejecutar.",
      },
      {
        name: "HyperX Pulsefire Dart",
        slug: "HyperX-Pulsefire-Dart",
        category: "Inalambrico", 
        image: "/img/mouse6.webp",
        price: 14000,
        rating: 2.4,
        countInStock: 34,
        description: "Mayor duración de la batería, con batería recargable incorporada que podés cargar fácilmente con el cable USB incluido sin necesidad de reemplazarla. Para prolongar la duración, usá el conmutador de encendido para apagar el mouse cuando no lo estés usando.",
      },
  ],
};

export default data;
